#dev; prod
spring.profiles.active: dev

## Server Properties
server:
  port: 8080

## App Properties
app:
  jwtSecret: secretKey
  jwtExpirationInMs: 604800000
  cors:
    allowedOrigins: http://localhost:4200

## Spring Properties
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ## Log SQL statements and parameters output
    show-sql: true
    properties.hibernate.format_sql: true




## Log Spring Cache output
logging.level.org.springframework.cache: TRACE

